### ISSUE TITLE
Merge and simplify Vector2D/3D with Point2D/3D

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc-builder#28]
Just keep Vector2D/3D. We don't need special point classes.

**Comment by Georspai** [comment]
To merge the `Point2D/3D`  classes into `Vector2D/3D`  classes, since they have the same attributes, we just had to: 

- Remove the Vector constructor from Point.
```
  /// TO_BE_REMOVED: Removing Point2D class 
  /// Create vector between origin and point (conversion from point).
  ///
  /// @param p The point
  explicit Vector2D(const Point2D &p) : x(p.x), y(p.y) {}
  ```

-   Change the Vector constructor from 2 Points, to take 2 Vectors as input. 
```
  /// CHANGED: Removing Point2D class 
  /// Create vector between points.
  ///
  /// @param p First point
  /// @param q Second point
  explicit Vector2D(const Vector2D &p, const Vector2D &q)
      : x(q.x - p.x), y(q.y - p.y) { }
```
- Add a bracket operator to the Vector classes that is used by the Point classes.
- Add a `size()` method  to the Vector classes that is used by the Point classes.
- Removed the minimal set of algebra for points functions from `Vector.h` since all this functionality already exists in the Vector classes. 

After that, changed all `Point2D/3D` objects to `Vector2D/3D` objects in src and tests and merged the Point and Vector pybind declarations in `dtcc_builder.cpp` .
```
  py::class_<DTCC_BUILDER::Vector3D>(m, "Vector3D")
      .def(py::init<>())
      .def("__repr__",
           [](const DTCC_BUILDER::Vector3D &p)
           {
             return "<Vector3D (" + DTCC_BUILDER::str(p.x) + ", " +
                    DTCC_BUILDER::str(p.y) + ", " + DTCC_BUILDER::str(p.z) +
                    ")>";
           })
      .def_readonly("x", &DTCC_BUILDER::Vector3D::x)
      .def_readonly("y", &DTCC_BUILDER::Vector3D::y)
      .def_readonly("z", &DTCC_BUILDER::Vector3D::z);
 ```
All the changes that were done for the 2D case were done for the 3D as well. 
 It builds and runs properly. If the changes don't seem right I can do it in an other way before pushing.
